apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: test-audio-to-text-secret-2
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/tpetkos/test-audio-to-text-secret-2:9de3a9b7f2b9d7e57807c0011443452531228257@sha256:02679c2f470e253d243e1ceb0dc23155c48dab0c146442916187cef0febf953f # use pre-built to bootstrap 
          name: app-inference
